redis-server:
  image: redis
  container_name: redis-server
  expose:
    - 6379
node:  
  container_name: nodejs-server
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis-server
  ports:
    - 3000:3000
  environment:
    - REDIS_URL=redis://redis-server
    - NODE_ENV=development
    - PORT=3000
  command:
    sh -c 'npm i && node src/server.js'

