apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server
    tier: frontend
spec:
  type: NodePort
  selector:
    app: server
    tier: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000