apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
      tier: frontend
  template:
    metadata:
      labels:
        app: server
        tier: frontend
    spec:
      containers:
      - name: server
        image: alsoares59/devops-project:latest
        ports:
          - containerPort: 3000
        env:
          - name: REDIS_URL
            value: redis-master
          - name: PORT
            value: "3000"