apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: node
  name: node
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: node
    spec:
      containers:
      - args:
        - sh
        - -c
        - npm i && node src/server.js
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "3000"
        - name: REDIS_URL
          value: redis://redis-server
        - name: REDIS_PORT
          value: "6397"
        image: node
        name: nodejs-server
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
