IMAGE_NAME = "centos/7" 
NODE_NAME = "devops-project-VM"

# NOTE: the installation process of Ansible and Vagrant comes from https://github.com/ginigangadharan/vagrant-iac-usecases/tree/master/virtualbox-minikube
# However, the kubernetes deployments, pods and services are configured by ourselves with the web application
Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
    end
    
    config.ssh.insert_key = true
    config.ssh.forward_agent = true

    config.vm.network "forwarded_port",
    guest: 3000,
    host:  3000,
    auto_correct: true

    config.vm.network "forwarded_port",
    guest: 45771,
    host:  45771,
    auto_correct: true

    config.vm.define NODE_NAME do |master|     
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "127.0.0.1"
        master.vm.hostname = NODE_NAME

        master.vm.synced_folder "../k8s/", "/home/k8s", type: "virtualbox", disabled: false

        master.vm.provision "ansible_local" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "playbooks/init-task.yaml"
            ansible.extra_vars = {
                node_ip: "127.0.0.1",
            }
        end
    end

end